/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_calljava_TestCallJavaObject */

#ifndef _Included_com_jni_calljava_TestCallJavaObject
#define _Included_com_jni_calljava_TestCallJavaObject
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_calljava_TestCallJavaObject
 * Method:    putString
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jni_calljava_TestCallJavaObject_putString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jni_calljava_TestCallJavaObject
 * Method:    putObject
 * Signature: (Lcom/jni/calljava/Student;)V
 */
JNIEXPORT void JNICALL Java_com_jni_calljava_TestCallJavaObject_putObject
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jni_calljava_TestCallJavaObject
 * Method:    insertObject
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_calljava_TestCallJavaObject_insertObject
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_calljava_TestCallJavaObject
 * Method:    testQuote
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_calljava_TestCallJavaObject_testQuote
        (JNIEnv *, jobject);

/*
 * Class:     com_jni_calljava_TestCallJavaObject
 * Method:    delQuote
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_calljava_TestCallJavaObject_delQuote
        (JNIEnv *, jobject);


#ifdef __cplusplus
}
#endif
#endif
