/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_test_Demo1 */

#ifndef _Included_com_jni_test_Demo1
#define _Included_com_jni_test_Demo1
#ifdef __cplusplus
extern "C" {
#endif
#undef com_jni_test_Demo1_A
#define com_jni_test_Demo1_A 100L
/*
 * Class:     com_jni_test_Demo1
 * Method:    getStringPwd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_test_Demo1_getStringPwd
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_test_Demo1
 * Method:    getStringPwd2
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_test_Demo1_getStringPwd2
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_test_Demo1
 * Method:    changeName
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_test_Demo1_changeName
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_test_Demo1
 * Method:    changeAge
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_test_Demo1_changeAge
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_test_Demo1
 * Method:    callAddMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_test_Demo1_callAddMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
