/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_thread_TestDemo */

#ifndef _Included_com_jni_thread_TestDemo
#define _Included_com_jni_thread_TestDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_thread_TestDemo
 * Method:    naitveThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_naitveThread
        (JNIEnv *, jobject);

/*
 * Class:     com_jni_thread_TestDemo
 * Method:    closeThread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_closeThread
        (JNIEnv *, jobject);


/*
 * Class:     com_jni_thread_TestDemo
 * Method:    nativeFun1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_nativeFun1
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_thread_TestDemo
 * Method:    nativeFun2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_nativeFun2
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_thread_TestDemo
 * Method:    staticFun3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_staticFun3
  (JNIEnv *, jclass);

/*
 * Class:     com_jni_thread_TestDemo
 * Method:    staticFun4
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_thread_TestDemo_staticFun4
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
