/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jni_dynamic_register_TestDemo */

#ifndef _Included_com_jni_dynamic_register_TestDemo
#define _Included_com_jni_dynamic_register_TestDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jni_dynamic_register_TestDemo
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jni_dynamic_register_TestDemo_stringFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_dynamic_register_TestDemo
 * Method:    staticRegister
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jni_dynamic_register_TestDemo_staticRegister
  (JNIEnv *, jobject);

/*
 * Class:     com_jni_dynamic_register_TestDemo
 * Method:    dynamicJavaMethod01
 * Signature: ()V
 *//*
JNIEXPORT void JNICALL Java_com_jni_dynamic_register_TestDemo_dynamicJavaMethod01
  (JNIEnv *, jobject);

*//*
 * Class:     com_jni_dynamic_register_TestDemo
 * Method:    dynamicJavaMethod02
 * Signature: (Ljava/lang/String;)I
 *//*
JNIEXPORT jint JNICALL Java_com_jni_dynamic_register_TestDemo_dynamicJavaMethod02
  (JNIEnv *, jobject, jstring);*/

#ifdef __cplusplus
}
#endif
#endif
